services:
  app:
    build: .
    container_name: expense-tracker-app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: expense_tracker
      DB_PASSWORD: postgres
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: expense-tracker-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expense_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: